"""Machine-readable personal-data inventory (mirrors docs/privacy/data-inventory.md).

Legal basis fields that depend on the commercial model stay
``UNSPECIFIED / LEGAL REVIEW``. Do not invent Art. 6 grounds here.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


LEGAL_REVIEW = "UNSPECIFIED / LEGAL REVIEW"


@dataclass(frozen=True)
class DataClassRecord:
    id: str
    label: str
    source: str
    data_subjects: str
    purpose: str
    storage: str
    cloud_transfer: str
    retention: str
    pii: str  # none | low | high | secret
    special_category_risk: str
    deletion_trigger: str
    security: str
    processor: str
    legal_basis: str = LEGAL_REVIEW
    export_path: str = ""
    notes: str = ""


DATA_INVENTORY: tuple[DataClassRecord, ...] = (
    DataClassRecord(
        id="profile",
        label="Profil (Name, Kontakt, Adresse, Berufswunsch)",
        source="User input (Profile UI) / CV import",
        data_subjects="Applicant (end user)",
        purpose="Job matching, applications, cover letters",
        storage="AppData config YAML + meta.json",
        cloud_transfer="None by Karrierekrake (local only)",
        retention="Until user deletes profile / delete-all",
        pii="high",
        special_category_risk="Possible if user enters health/religion etc. — not solicited",
        deletion_trigger="delete_profile / delete_all",
        security="Local disk ACL; redaction in logs",
        processor="None (local processing). Google only if user connects Gmail.",
        export_path="export.profile",
    ),
    DataClassRecord(
        id="address_contact",
        label="Adresse / Kontakt",
        source="Profile fields",
        data_subjects="Applicant",
        purpose="Applications, location filters",
        storage="AppData config YAML",
        cloud_transfer="None local; may appear in user-sent applications",
        retention="Until profile delete",
        pii="high",
        special_category_risk="Low (address alone)",
        deletion_trigger="delete_profile / delete_all",
        security="Local disk; log redaction",
        processor="None",
        export_path="export.profile",
    ),
    DataClassRecord(
        id="work_experience",
        label="Berufserfahrung / Qualifikationen",
        source="CV parse + manual edit",
        data_subjects="Applicant",
        purpose="Matching, cover letters, evidence",
        storage="AppData config YAML",
        cloud_transfer="None (local LLM optional)",
        retention="Until profile/document delete",
        pii="high",
        special_category_risk="Possible via free-text CV content",
        deletion_trigger="delete_profile / delete_document / delete_all",
        security="Local; Günther logs event codes only",
        processor="None (local AI if enabled)",
        export_path="export.profile",
    ),
    DataClassRecord(
        id="cv_files",
        label="CV / DOCX / PDF Dateien",
        source="User upload",
        data_subjects="Applicant",
        purpose="Applications, parsing",
        storage="AppData cvs/ (+ cover_letters/)",
        cloud_transfer="None by app; user may attach to external ATS",
        retention="Until document delete / delete-all",
        pii="high",
        special_category_risk="Possible in document content",
        deletion_trigger="delete_document / clear_cv_storage / delete_all",
        security="Local files; secure_temp for parse",
        processor="None",
        export_path="export.documents_meta (files optional with confirm)",
    ),
    DataClassRecord(
        id="cv_extracted_text",
        label="Extrahierter CV-Text",
        source="Local PDF/DOCX parsers",
        data_subjects="Applicant",
        purpose="Populate profile; Günther assist",
        storage="Ephemeral / profile YAML after import",
        cloud_transfer="None",
        retention="Until profile wipe; temps wiped after parse",
        pii="high",
        special_category_risk="Same as CV",
        deletion_trigger="delete_profile / delete_all",
        security="secure_temp + parser limits",
        processor="None",
        export_path="export.profile",
    ),
    DataClassRecord(
        id="jobs",
        label="Jobs / Suchergebnisse",
        source="Job boards / adapters (HTTP)",
        data_subjects="Typically public vacancy data; may include recruiter emails in text",
        purpose="Search, match, apply preview",
        storage="SQLite jobs.db table jobs",
        cloud_transfer="Outbound fetch only; no upload of profile by search itself",
        retention="Until clear_job_data / delete_all",
        pii="low",
        special_category_risk="Unlikely",
        deletion_trigger="clear_jobs / delete_all",
        security="Local SQLite",
        processor="Job board operators (independent controllers of vacancy pages)",
        export_path="export.jobs_summary",
    ),
    DataClassRecord(
        id="application_cases",
        label="ApplicationCases / Lifecycle",
        source="User apply flow + mail association",
        data_subjects="Applicant; employer contacts in events",
        purpose="Track applications and replies",
        storage="SQLite application_cases, case_events, lifecycle_*",
        cloud_transfer="None local",
        retention="Until case delete / delete_all",
        pii="high",
        special_category_risk="Low–medium via mail-derived notes",
        deletion_trigger="delete_application_case / delete_all",
        security="Local SQLite",
        processor="None",
        export_path="export.cases",
    ),
    DataClassRecord(
        id="mail_content",
        label="Mailinhalte (Gmail sync cache)",
        source="Gmail API (user-authorized)",
        data_subjects="Applicant; senders (recruiters/employers)",
        purpose="Lifecycle classification & association",
        storage="SQLite email_messages",
        cloud_transfer="Download from Google; no re-upload of bodies by Karrierekrake",
        retention="Until mailcache delete / disconnect / delete_all",
        pii="high",
        special_category_risk="Possible in message bodies",
        deletion_trigger="delete_mail_cache / disconnect_google / delete_all",
        security="Local DB; bodies never logged",
        processor="Google (Gmail) as processor of mailbox; local app as separate processing",
        export_path="export.mail_meta (bodies only with explicit PII confirm)",
    ),
    DataClassRecord(
        id="calendar_freebusy",
        label="Calendar FreeBusy / Event-Entwürfe",
        source="Google Calendar FreeBusy API; local scheduling proposals",
        data_subjects="Applicant busy times; interview parties in drafts",
        purpose="Interview slot proposals (user-approved writes only)",
        storage="Ephemeral in-memory FreeBusy; drafts may appear in lifecycle events; no dedicated FreeBusy table",
        cloud_transfer="FreeBusy query to Google; event create only after explicit user approve",
        retention="Session / until disconnect / delete_calendar_cache clears cache dir + related lifecycle noise",
        pii="high",
        special_category_risk="Health appointments could appear in FreeBusy — treat as sensitive",
        deletion_trigger="delete_calendar_cache / disconnect_google / delete_all",
        security="No persistent FreeBusy store; OAuth in keyring",
        processor="Google Calendar",
        export_path="export.calendar_note",
        notes="If a future FreeBusy disk cache is added, it MUST register here first.",
    ),
    DataClassRecord(
        id="oauth_tokens",
        label="OAuth Tokens",
        source="Google OAuth (user consent)",
        data_subjects="Applicant account identifiers in token payload",
        purpose="Gmail readonly + optional Calendar FreeBusy/write scopes",
        storage="OS keyring only (legacy oauth_*.json wiped)",
        cloud_transfer="Token refresh/revoke with Google",
        retention="Until disconnect / token delete / delete_all",
        pii="secret",
        special_category_risk="None as such",
        deletion_trigger="delete_oauth_tokens / disconnect_google / delete_all",
        security="OS credential store; never exported",
        processor="Google",
        export_path="(never)",
    ),
    DataClassRecord(
        id="hr_contacts",
        label="HR-Kontakte / Recruiting contacts",
        source="Public page extraction / discovery",
        data_subjects="HR/recruiters (third parties)",
        purpose="Contact suggestions for applications",
        storage="SQLite recruiting_contacts",
        cloud_transfer="Fetch of public pages only",
        retention="Until contacts invalidated/deleted / delete_all",
        pii="high",
        special_category_risk="Low",
        deletion_trigger="delete_hr_contacts / delete_all",
        security="Local SQLite",
        processor="None (public sources)",
        export_path="export.hr_contacts",
    ),
    DataClassRecord(
        id="logs",
        label="Logs",
        source="Application runtime",
        data_subjects="May incidentally contain PII if mislogged",
        purpose="Debugging, support by user",
        storage="AppData logs/",
        cloud_transfer="None (no crash telemetry shipped)",
        retention="Until delete_logs / delete_all",
        pii="low–high (policy: redact secrets/PII)",
        special_category_risk="Should be none if policy held",
        deletion_trigger="delete_logs / delete_all",
        security="SecretRedactionFilter on karrierekrake.*",
        processor="None",
        export_path="export.logs_meta",
    ),
    DataClassRecord(
        id="exports",
        label="Exports (user-created privacy bundles)",
        source="Privacy export action",
        data_subjects="Applicant",
        purpose="Data portability / user backup",
        storage="User-chosen path (not AppData by default)",
        cloud_transfer="None by app",
        retention="User-controlled",
        pii="high",
        special_category_risk="Same as included classes",
        deletion_trigger="User deletes export files; app does not retain copies",
        security="ExportGate denies secrets; PII requires confirm",
        processor="None",
        export_path="n/a",
    ),
    DataClassRecord(
        id="backups",
        label="Wipe backups (.wipe_backup_*)",
        source="Legacy wipe path (config snapshot)",
        data_subjects="Applicant",
        purpose="Rollback aid after wipe — privacy delete_all avoids creating PII backups",
        storage="AppData root .wipe_backup_*",
        cloud_transfer="None",
        retention="Until removed by delete_all / manual",
        pii="high",
        special_category_risk="Possible",
        deletion_trigger="delete_all removes wipe backups",
        security="Secrets excluded from wipe backup copy",
        processor="None",
        export_path="n/a",
        notes="PrivacyLifecycleService.delete_all defaults to no new backup.",
    ),
    DataClassRecord(
        id="payment_account",
        label="Payment / Account",
        source="—",
        data_subjects="—",
        purpose="—",
        storage="NOT PRESENT in this codebase",
        cloud_transfer="None",
        retention="n/a",
        pii="none",
        special_category_risk="n/a",
        deletion_trigger="n/a",
        security="n/a",
        processor="n/a",
        legal_basis=LEGAL_REVIEW,
        notes="No payment processor integrated. If added later: STOP and extend inventory.",
    ),
    DataClassRecord(
        id="support_crash",
        label="Support / Crash reports",
        source="—",
        data_subjects="—",
        purpose="—",
        storage="NOT PRESENT — no Sentry/telemetry/crash uploader",
        cloud_transfer="None",
        retention="n/a",
        pii="none",
        special_category_risk="n/a",
        deletion_trigger="n/a",
        security="Policy: no PII crash reports by default",
        processor="n/a",
        notes="Hidden telemetry is forbidden. Local logs only.",
    ),
    DataClassRecord(
        id="browser_profile",
        label="Playwright browser profile / cache",
        source="Automated browser sessions",
        data_subjects="May hold session cookies for job sites",
        purpose="Apply/search automation",
        storage="AppData browser_profile/, browsers/, cache/",
        cloud_transfer="To visited sites only (user-driven automation)",
        retention="Until delete_browser_cache / delete_all",
        pii="low–high (cookies)",
        special_category_risk="Low",
        deletion_trigger="delete_browser_cache / delete_all",
        security="Local disk",
        processor="Visited site operators",
        export_path="(not in default export)",
    ),
    DataClassRecord(
        id="models",
        label="Local LLM model weights",
        source="User download (Günther)",
        data_subjects="None in weights",
        purpose="Local inference",
        storage="AppData models/",
        cloud_transfer="Download from configured model URL only when user confirms",
        retention="Until user uninstalls models / delete_all",
        pii="none",
        special_category_risk="None",
        deletion_trigger="delete_models / delete_all",
        security="SHA-256 verify on install",
        processor="Model host (download only)",
        export_path="(not exported)",
    ),
)


def lookup_record(record_id: str) -> DataClassRecord | None:
    for row in DATA_INVENTORY:
        if row.id == record_id:
            return row
    return None


def inventory_as_dicts() -> list[dict[str, Any]]:
    return [asdict(r) for r in DATA_INVENTORY]
